apiVersion: apps/v1 #beta2 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: browser
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: firefox
  replicas: 1 # tells deployment to run 1 pods matching the template
  template: # create pods using pod definition in this template
    metadata:
      labels:
        app: firefox
    spec:
      hostNetwork: true
      containers:
      - name: firefox
        image: elastestbrowsers/firefox
        ports:
        - containerPort: 5900
      nodeSelector:
        networking: host
---
apiVersion: v1
kind: Service
metadata:
  name: browser-svc
  labels:
    app: firefox
spec:
  ports:
    - port: 5900
      protocol: TCP
      name: vnc-port
  selector:
    app: firefox
  type: NodePort